AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Battle of the extension sam template.

Globals:
  Function:
    Timeout: 3

Parameters:
  LLRTLayerArn:
    Type: String
    Description: The ARN of the Lambda Layer with LLRT extension
  NodeLayerArn:
    Type: String
    Description: The ARN of the Lambda Layer with Node extension
  RustLayerArn:
    Type: String
    Description: The ARN of the Lambda Layer with Rust extension

Resources:
  TestLLRTExtensionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test-lambda/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          SQS_URL: !Ref AnalyticsSQS
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnalyticsSQS.QueueName
      Layers:
        - !Ref LLRTLayerArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
          - app.ts
  TestNodeExtensionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test-lambda/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          SQS_URL: !Ref AnalyticsSQS
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnalyticsSQS.QueueName
      Layers:
        - !Ref NodeLayerArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
          - app.ts
  TestRustExtensionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test-lambda/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          SQS_URL: !Ref AnalyticsSQS
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnalyticsSQS.QueueName
      Layers:
        - !Ref RustLayerArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
          - app.ts

  AnalyticsSQS:
    Type: AWS::SQS::Queue
