AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Battle of the extension sam template.

Globals:
  Function:
    Timeout: 10

Parameters:
  LLRTLayerArn:
    Type: String
    Description: The ARN of the Lambda Layer with LLRT extension
  RustLayerArn:
    Type: String
    Description: The ARN of the Lambda Layer with Rust extension

Resources:
  NonExtensionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send-analytics-lambda/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      Environment:
        Variables:
          SQS_URL: !Ref AnalyticsSQS
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnalyticsSQS.QueueName

  TestLLRTExtensionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test-lambda/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      Environment:
        Variables:
          SQS_URL: !Ref AnalyticsSQS
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnalyticsSQS.QueueName
      Layers:
        - !Ref LLRTLayerArn

  TestRustExtensionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test-lambda/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      Environment:
        Variables:
          SQS_URL: !Ref AnalyticsSQS
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnalyticsSQS.QueueName
      Layers:
        - !Ref RustLayerArn

  AnalyticsSQS:
    Type: AWS::SQS::Queue
